# -*- coding: utf-8 -*-
"""Data Cleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18p5aja5RO9id6nsfsXqeST8kNI0H_0tT
"""

from google.colab import files
Uploaded=files.upload()

"""**READING THE FILE**"""

import pandas as pd
df=pd.read_csv('Bank_Churn.csv')
print(df.to_string())

"""**CLEANING THE DATA**"""

# first checking null values
df.isnull()
#no null values

#checking for duplicate rows
df.duplicated()

df.info()

#checking the stastics
df.describe()

df["Exited"].value_counts()
# most people retain with the bank

#checking do females leave more or men
df.groupby("Gender")["Exited"].value_counts()

#analysing by age groups
df.groupby("Age")["Exited"].value_counts()

# checking which age group people left the most
df[df["Exited"]==1]["Age"].max()

#complete summary for exited customers
df[df["Exited"]==1].describe()

#summary for retained customers
df[df["Exited"]==0].describe()

pd.crosstab(df["Gender"],df["Exited"])

pd.crosstab(df["IsActiveMember"],df["Exited"])

pd.crosstab(df["HasCrCard"],df["Exited"])

"""**FACTORS AFFECTING CHURN**"""

df.groupby("Exited")["Age"].mean()

df.groupby("Exited")["HasCrCard"].mean()

df.groupby("Exited")["CreditScore"].mean()

df.groupby("Exited")["NumOfProducts"].mean()

df.groupby("Exited")["Tenure"].mean()

"""**VISUALIZATIONS**

"""

import seaborn as sns
sns.histplot(df["Age"])

sns.boxplot(x="Exited",y="Age",data=df)

sns.boxplot(x="Exited",y="HasCrCard",data=df)

sns.boxplot(x="Exited",y="Geography",data=df)

sns.boxplot(x="Exited",y="Balance",data=df)

sns.boxplot(x="Exited",y="EstimatedSalary",data=df)